config/routes.rb
CronerWebApp::Application.routes.draw do

  resources :summary_attendances
  get '/generate_summaries', to: 'summary_attendances#generate_summaries'
  get '/export_summaries', to: 'summary_attendances#export_summaries'
  
  resources :branch_offices

  resources :employees do
    resources :attendances
    resources :devices
  end

  resources :customers

  devise_for :users, :controllers => { registrations: 'registrations' }

  

  root 'home#index'

end

app/models/employee.rb
class Employee < ActiveRecord::Base
	include Filterable
	include Importable
	include Exportable

	belongs_to :customer

	has_many :workplaces
	has_many :branch_offices, :through => :workplaces
	has_many :devices
	has_many :attendances
	has_many :summary_attendances
	
	has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  	  	validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/

	# Validations
			# validates :worker_id, <validations>
			validates :run, presence: true
			# validates :names, <validations>
			# validates :lastnames, <validations>
			validates :email, presence: true
			# validates :addres, <validations>
			# validates :birthdate, <validations>
	
	# Scopes (used for search form)
	#   To search by full text use { where("attribute like ?", "%#{attribute}%") }
	#   To search by string use { where attribute: attribute }
		scope :worker_id, -> (worker_id) { where worker_id: worker_id }
		scope :run, -> (run) { where run: run }
		scope :names, -> (names) { where names: names }
		scope :lastnames, -> (lastnames) { where lastnames: lastnames }
		scope :email, -> (email) { where email: email }
		scope :addres, -> (addres) { where addres: addres }
		scope :birthdate, -> (birthdate) { where birthdate: birthdate }
	
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :set_employee, only: [:show, :edit, :update, :destroy]

  # GET /employees
  def index
    # @employees = Employee.all
  end

  # GET /employees/1
  def show
  end

  # GET /employees/new
  def new
    @employee = Employee.new
  end

  # GET /employees/1/edit
  def edit
  end

  # POST /employees
  def create
    # @branch_office = @customer.branch_offices.find(params[:branch_office_id])
    
    @employee = @customer.employees.new(employee_params)

    # @workerplace = Workplace.new
    # @workerplace.employee = @employee
    # @workerplace.branch_office = @branch_office

     if @employee.save # and @workerplace.save
      redirect_to @employee, notice: 'Empleado registrado satisfactoriamente.'
    else
      render :new, notice: 'No se pudo registrar el empleado.'
    end
  end

  # PATCH/PUT /employees/1
  def update
    if @employee.update(employee_params)
      redirect_to @employee, notice: 'Employee was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /employees/1
  def destroy
    @employee = @customer.employees.find(params[:id])
    @employee.destroy
    redirect_to employees_url, notice: 'Employee was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_employee
      @employee = Employee.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def employee_params
      params.require(:employee).permit(:worker_id, :run, :names, :lastnames, :email, :addres, :birthdate, :contract_type, :weekly_hours, :avatar, :branch_office_id)
    end
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/views/employees/_form.html.erb
<%= form_for @employee, :url => employees_path, :html => { :multipart => true } do |f| %>
<% if @employee.errors.any? %>
<div id="error_explanation">
    <h2><%= pluralize(@employee.errors.count, "error") %> prohibited this employee from being saved:</h2>

    <ul>
        <% @employee.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
        <% end %>
    </ul>
</div>
<% end %>

<!-- <div class="form-group">
          <= f.label :customer_id %>
          <= select("employee", "customer_id", Customer.all.collect {|p| [ p.name, p.id ] }, {include_blank: 'None'}) %>
        </div> -->

<div class="form-group">
                <%= f.label :worker_id %>
            <%= f.text_field :worker_id, :class => "form-control" %>
    </div>
<!-- <div class="form-group">
                <= f.label :branch_office_id %>
            <= f.collection_select :branch_office_id, @customer.branch_offices, :id, :name, prompt: true, :class => 'form-control'  %>
</div> -->
<div class="form-group">
                <%= f.label :contract_type %>
            <%= f.text_field :contract_type, :class => "form-control" %>
    </div>
<div class="form-group">
                <%= f.label :weekly_hours %>
            <%= f.text_field :weekly_hours, :class => "form-control" %>
    </div>
<div class="form-group">
                <%= f.label :run %>
            <%= f.text_field :run, :class => "form-control" %>
    </div>
<div class="form-group">
                <%= f.label :names %>
            <%= f.text_field :names, :class => "form-control" %>
    </div>
<div class="form-group">
                <%= f.label :lastnames %>
            <%= f.text_field :lastnames, :class => "form-control" %>
    </div>
<div class="form-group">
                <%= f.label :email %>
            <%= f.text_field :email, :class => "form-control" %>
    </div>
<div class="form-group">
                <%= f.label :addres %>
            <%= f.text_field :addres, :class => "form-control" %>
    </div>
<div class="form-group">
                <%= f.label :birthdate %>
            <%= f.date_select :birthdate, :class => "form-control" %>
    </div>
<div class="form-group">
            <%= f.label :avatar %>
            <%= f.file_field :avatar %>
    </div>
<div class="actions">
    <%= f.submit :class => "btn btn-success" %>
</div>
<% end %>

app/views/employees/edit.html.erb
<h1>Editing employee</h1>

<%= render 'form' %>

<%= link_to 'Show', @employee, :class => "bnt btn-link" %> |
<%= link_to 'Back', employees_path, :class => "btn btn-link" %>

app/views/employees/index.html.erb
<h2 class="page-title page-title-green">
  <span class="glyphicon glyphicon-user"></span>
  empleados
</h2>

<div class="page-buttons clearfix">
  <%= link_to 'Nuevo Empleado', new_employee_path, :class => "btn btn-primary float-left" %>
</div>

<div class="page-body">
  <div class="panel panel-default">
    <div class="panel-body">
      <div class="table-responsive">

        <table class="table table-hover">
          <thead>
            <tr>
                              <th>CodTrabajador</th>
                              <th>Run</th>
                              <th>Names</th>
                              <th>Lastnames</th>
                              <th>Horas/Semana</th>
                              <!-- <th>Email</th> -->
                              <!-- <th>Addres</th>
                              <th>Birthdate</th> -->
                            <th></th>              
            </tr>
          </thead>

          <tbody>
            <% @customer.employees.each do |employee| %>
              <tr>
                                    <td><%= employee.worker_id %></td>
                                    <td><%= employee.run %></td>
                                    <td><%= employee.names %></td>
                                    <td><%= employee.lastnames %></td>
                                    <td><%= employee.weekly_hours %></td>
                                    <!-- <td><%= employee.addres %></td>
                                    <td><%= employee.birthdate %></td> -->
                                <td><%= link_to '', employee, :class => "btn btn-default glyphicon glyphicon-eye-open" %>
                                </td>
                <!-- <td><= link_to 'Edit', edit_employee_path(employee) %></td>
                <td><= link_to 'Destroy', employee, method: :delete, data: { confirm: 'Are you sure?' } %></td> -->
              </tr>
            <% end %>
          </tbody>
        </table>

      </div>
    </div>
  </div>
</div>

<br>

app/views/employees/new.html.erb
<h1>New employee</h1>

<%= render 'form' %>

<%= link_to 'Back', employees_path, :class => "btn btn-link" %>

app/views/employees/show.html.erb
<h2 class="page-title page-title-green">
	<span class="glyphicon glyphicon-user"></span>
	empleados
</h2>


<div class="page-body">
	<div class="row">
		<div class="col-md-7">
			<div class="panel panel-success">
				<div class="panel-heading">Datos empleado</div>
				<div class="panel-body">

					<div class="row well">
						<center>
							<%= image_tag @employee.avatar.url(:medium) %>
						</center>
					</div>

					<div class="panel panel-default">
						<dl class="dl-horizontal">
							<dt>Cod Trabajador:</dt>
							<dd><%= @employee.worker_id %></dd>

							<dt>Tipo de contrato:</dt>
							<dd><%= @employee.contract_type %></dd>

							<dt>Horas semanales:</dt>
							<dd><%= @employee.weekly_hours %></dd>

							<dt>Run:</dt>
							<dd><%= @employee.run %></dd>

							<dt>Nombres:</dt>
							<dd><%= @employee.names %></dd>

							<dt>Apellidos:</dt>
							<dd><%= @employee.lastnames %></dd>

							<dt>Correo electrónico</dt>
							<dd><%= @employee.email %></dd>

							<dt>Dirección:</dt>
							<dd><%= @employee.addres %></dd>

							<dt>Fecha nacimiento:</dt>
							<dd><%= @employee.birthdate %></dd>
						</dl>
					
					</div>


<%= link_to 'Editar', edit_employee_path(@employee), :class => "btn btn-default" %>
<%= link_to 'Destruir', @employee, method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-danger" %>
<%= link_to 'Volver', employees_path, :class => "btn btn-link" %>

				</div>
			</div>
		
			<!-- <div class="panel panel-success">
				<div class="panel-heading">Sucursales</div>
				<div class="panel-body">
					<div class="table-responsive">
						<table class="table table-hover">
							<thead>
								<tr>
									<th>Sucursal</th>
								    <th></th>              
								</tr>
							</thead>
							<tbody>
								 	<% @employee.branch_offices.each do |bo| %>
								  	<tr>
								    	<td><%= bo.name %></td>
								   		<td></td>
							 	<% end %>
							</tbody>
						</table>
					</div>
				</div>
			</div>
 -->
			<div class="panel panel-success">
				<div class="panel-heading">Smart-Devices</div>
				<div class="panel-body">
					<div class="table-responsive">
						<div class="page-buttons clearfix">
						  <%= link_to 'Nuevo dispositivo', new_employee_device_path(@employee), :class => "btn btn-primary float-left" %>
						</div>
				        <table class="table table-hover">
				          <thead>
				            <tr>
								<th>Imei</th>
	                            <th></th>              
				            </tr>
				          </thead>

				          <tbody>
				            <% @employee.devices.each do |device| %>
				              	<tr>
                                	<td><%= device.imei %></td>
                               		<td>
		                                <!-- 	<= link_to '', employee_device_path(@employee, device), :class => "glyphicon glyphicon-eye-open" %> -->
		                                <button type="button" class="glyphicon glyphicon-eye-open" data-toggle="modal" data-target=".bs-example-modal-sm"> </button>
	                                </td>


									<!-- Modal para el detalle del smart-device -->

									<div class="modal fade bs-example-modal-sm" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel" aria-hidden="true">
									  <div class="modal-dialog modal-sm">
									    <div class="modal-content">
									    	<div class="modal-header">
										        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
										        <h4 class="modal-title">Detalle del dispositivo inteligente</h4>
									      	</div>
											<div class="panel panel-success">
												<div class="panel-body">				
									  
													<b>Meid:</b> <%= device.meid %>	<br />
													<b>Esn:</b> <%= device.esn %>	<br />
													<b>Imei:</b> <%= device.imei %>	<br />
													<b>Wlanmacaddress:</b> <%= device.wlanMacAddress %>	<br />
												</div>
											</div>

									    </div>	<!-- Modal Content  -->
									  </div>	<!-- Modal Dialog  -->
									</div>	<!-- Modal Fade  -->
				                <!-- <td><= link_to 'Edit', edit_device_path(device) %></td>
				                <td><= link_to 'Destroy', device, method: :delete, data: { confirm: 'Are you sure?' } %></td> -->
				              </tr>
				            <% end %>
				          </tbody>
				        </table>

				      </div>	<!-- Table Responsive  -->
				    </div>	<!-- Panle Body  -->
				</div>	<!-- Panel success  -->

		</div>

		<div class="col-md-5">

			<div class="panel panel-success">
				<div class="panel-heading">Registros asistenciales</div>
				<div class="panel-body">
					<div class="table-responsive">

						<table class="table table-hover">
				          <thead>
				            <tr>
				                              <th>Evento</th>
				                              <th>Fecha de marcado</th>
				                            <th></th>              
				            </tr>
				          </thead>

				          <tbody>
				            <% @employee.attendances.order("marked_at desc").each do |attendance| %>
				              <tr>
				                                    <td><%= attendance.event %></td>
				                                    <td><%= attendance.marked_at %></td>
				                                <td>
				                                	<%= link_to '', employee_attendance_path(@employee, attendance), :class => "btn btn-default glyphicon glyphicon-eye-open" %>
				                                </td>
				                <!-- <td><= link_to 'Edit', edit_attendance_path(attendance) %></td>
				                <td><= link_to 'Destroy', attendance, method: :delete, data: { confirm: 'Are you sure?' } %></td> -->
				              </tr>
				            <% end %>
				          </tbody>
				        </table>

					</div>
				</div>
			</div>	

			
		</div>
			
	</div> <!-- row -->


		
</div>
	