config/routes.rb
CronerWebApp::Application.routes.draw do

  resources :summary_attendances
  get '/generate_summaries', to: 'summary_attendances#generate_summaries'
  get '/export_summaries', to: 'summary_attendances#export_summaries'
  
  resources :branch_offices

  resources :employees do
    resources :attendances
    resources :devices
  end

  resources :customers

  devise_for :users, :controllers => { registrations: 'registrations' }

  

  root 'home#index'

end

app/models/device.rb
class Device < ActiveRecord::Base
	include Filterable
	include Importable
	include Exportable

	belongs_to :employee
		
	# Validations
			# validates :meid, <validations>
			# validates :esn, <validations>
			validates :imei, presence: true
			# validates :wlanMacAddress, <validations>
			# validates :employee, <validations>
	
	# Scopes (used for search form)
	#   To search by full text use { where("attribute like ?", "%#{attribute}%") }
	#   To search by string use { where attribute: attribute }
		scope :meid, -> (meid) { where meid: meid }
		scope :esn, -> (esn) { where esn: esn }
		scope :imei, -> (imei) { where imei: imei }
		scope :wlanMacAddress, -> (wlanMacAddress) { where wlanMacAddress: wlanMacAddress }
		scope :employee, -> (employee_name) { where("employee.name like ?", "%#{employee_name}%") }
	
end

app/controllers/devices_controller.rb
class DevicesController < ApplicationController
  before_action :set_device, only: [:show, :edit, :update, :destroy]

  # GET /devices
  def index
    @employee = Employee.find(params[:employee_id])
    @devices = Device.all
  end

  # GET /devices/1
  def show
    @employee = Employee.find(params[:employee_id])
  end

  # GET /devices/new
  def new
    @employee = Employee.find(params[:employee_id])
    @device = Device.new
  end

  # GET /devices/1/edit
  def edit
    @employee = Employee.find(params[:employee_id])
  end

  # POST /devices
  def create
    @employee = Employee.find(params[:employee_id])
    @device = @employee.devices.new(device_params)

    if @device.save
      redirect_to @employee, notice: 'Dispositivo registrado exitosamente.'
    else
      render :new
    end
  end

  # PATCH/PUT /devices/1
  def update
    if @device.update(device_params)
      redirect_to [@employee, @employee.devices.build], notice: 'Device was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /devices/1
  def destroy
    @employee = Employee.find(params[:employee_id])
    @device = @employee.devices.find(params[:id])
    @device.destroy
    redirect_to @employee, notice: 'Device was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_device
      @device = Device.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def device_params
      params.require(:device).permit(:meid, :esn, :imei, :wlanMacAddress, :employee_id)
    end
end

app/helpers/devices_helper.rb
module DevicesHelper
end

app/views/devices/_form.html.erb
<%= form_for([@employee, @employee.devices.build]) do |f| %>
<% if @device.errors.any? %>
<div id="error_explanation">
    <h2><%= pluralize(@device.errors.count, "error") %> prohibited this device from being saved:</h2>

    <ul>
        <% @device.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
        <% end %>
    </ul>
</div>
<% end %>

<div class="form-group">
                <%= f.label :meid %>
            <%= f.text_field :meid, :class => "form-control" %>
    </div>
<div class="form-group">
                <%= f.label :esn %>
            <%= f.text_field :esn, :class => "form-control" %>
    </div>
<div class="form-group">
                <%= f.label :imei %>
            <%= f.text_field :imei, :class => "form-control" %>
    </div>
<div class="form-group">
                <%= f.label :wlanMacAddress %>
            <%= f.text_field :wlanMacAddress, :class => "form-control" %>
    </div>
<!-- <div class="form-group">
                <= f.label :employee_id %>
            <= f.collection_select :employee_id, Employee.all, :id, :name, prompt: true, :class => 'form-control'  %>
    </div> -->
<div class="actions">
    <%= f.submit :class => "btn btn-success" %>
</div>
<% end %>

app/views/devices/edit.html.erb
<h1>Editing device</h1>

<%= render 'form' %>

<%= link_to 'Show', @device, :class => "bnt btn-link" %> |
<%= link_to 'Back', employee_devices_path, :class => "btn btn-link" %>

app/views/devices/index.html.erb
<h2 class="page-title page-title-green">
  <span class="glyphicon glyphicon-phone"></span>
  Aparatos inteligentes
</h2>

<div class="page-buttons clearfix">
  <%= link_to 'New Device', new_employee_device_path, :class => "btn btn-primary float-left" %>
</div>

<div class="page-body">
  <div class="panel panel-default">
    <div class="panel-body">
      <div class="table-responsive">

        <table class="table table-hover">
          <thead>
            <tr>
                              <th>Meid</th>
                              <th>Esn</th>
                              <th>Imei</th>
                              <th>Wlanmacaddress</th>
                              <th>Employee</th>
                            <th></th>              
            </tr>
          </thead>

          <tbody>
            <% @employee.devices.each do |device| %>
              <tr>
                                    <td><%= device.meid %></td>
                                    <td><%= device.esn %></td>
                                    <td><%= device.imei %></td>
                                    <td><%= device.wlanMacAddress %></td>
                                    <td><%= device.employee.run %></td>
                                <td><%= link_to '', employee_device_path(@employee, device), :class => "glyphicon glyphicon-eye-open" %></td>
                <!-- <td><= link_to 'Edit', edit_device_path(device) %></td>
                <td><= link_to 'Destroy', device, method: :delete, data: { confirm: 'Are you sure?' } %></td> -->
              </tr>
            <% end %>
          </tbody>
        </table>

      </div>
    </div>
  </div>
</div>

<br>

app/views/devices/new.html.erb
<h2 class="page-title page-title-green">
    <span class="glyphicon glyphicon-user"></span>
    empleados
</h2>

<h1>New device</h1>

<%= render 'form' %>

<%= link_to 'Back', employee_devices_path, :class => "btn btn-link" %>

app/views/devices/show.html.erb
<h2 class="page-title page-title-green">
	<span class="glyphicon glyphicon-phone"></span>
	Aparatos inteligentes
</h2>

<div class="page-body">
	<div class="row">
		<div class="col-md-12">
			<div class="panel panel-primary">
				<div class="panel-heading">Detalle device</div>
				<div class="panel-body">

					<div class="row">
						<div class="col-md-6">
							<table class="table">
								<tbody>
																			<tr>
										  <th>Meid:</th>
										  <td><%= @device.meid %></td>
										</tr>
																			<tr>
										  <th>Esn:</th>
										  <td><%= @device.esn %></td>
										</tr>
																			<tr>
										  <th>Imei:</th>
										  <td><%= @device.imei %></td>
										</tr>
																			<tr>
										  <th>Wlanmacaddress:</th>
										  <td><%= @device.wlanMacAddress %></td>
										</tr>
																			<tr>
											<th>Employee:</th>
											<td><%= @device.employee.run %></td>
										</tr>
																	</tbody>
							</table>
						</div>

					</div>

<%= link_to 'Editar', edit_employee_device_path(@employee, @device), :class => "btn btn-default" %>
<%= link_to 'Destruir', [@device, @device.employee.build], method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-danger" %>
<%= link_to 'Volver', employee_devices_path, :class => "btn btn-link" %>

				</div>
			</div>
		</div>
	</div>
	
</div>