config/routes.rb
CronerWebApp::Application.routes.draw do

  resources :summary_attendances
  get '/generate_summaries', to: 'summary_attendances#generate_summaries'
  get '/export_summaries', to: 'summary_attendances#export_summaries'
  
  resources :branch_offices

  resources :employees do
    resources :attendances
    resources :devices
  end

  resources :customers

  devise_for :users, :controllers => { registrations: 'registrations' }

  

  root 'home#index'

end

app/models/attendance.rb
class Attendance < ActiveRecord::Base
	include Filterable
	include Importable
	include Exportable

	belongs_to :employee
		
	# Validations
			# validates :event, <validations>
			# validates :location, <validations>
			# validates :marked_at, <validations>
			# validates :employee, <validations>
	
	# Scopes (used for search form)
	#   To search by full text use { where("attribute like ?", "%#{attribute}%") }
	#   To search by string use { where attribute: attribute }
		scope :event, -> (event) { where event: event }
		scope :location, -> (location) { where location: location }
		scope :marked_at, -> (marked_at) { where marked_at: marked_at }
		scope :employee, -> (employee_name) { where("employee.name like ?", "%#{employee_name}%") }
	
end

app/controllers/attendances_controller.rb
class AttendancesController < ApplicationController
  before_action :set_attendance, only: [:show, :edit, :update, :destroy]

  # GET /attendances
  def index
    @attendances = Attendance.all
    @employee = Employee.find(params[:employee_id])
  end

  # GET /attendances/1
  def show
    @employee = Employee.find(params[:employee_id])
  end

  # GET /attendances/new
  def new
    @attendance = Attendance.new
    @employee = Employee.find(params[:employee_id])
  end

  # GET /attendances/1/edit
  def edit
    @employee = Employee.find(params[:employee_id])
    @attendance = @employee.attendances.find(params[:id])
  end

  # POST /attendances
  def create
    @employee = Employee.find(params[:employee_id])
    @attendance = @employee.attendances.new(attendance_params)

    if @attendance.save
      redirect_to [@employee, @employee.attendances.build], notice: 'Attendance was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /attendances/1
  def update
    @employee = Employee.find(params[:employee_id])
    @attendance = @employee.attendances.find(params[:id])

    if @@employee.attendances.find(params[:id]).update(attendance_params)
      redirect_to @employee, notice: 'Attendance was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /attendances/1
  def destroy
    @employee = Employee.find(params[:employee_id])
    @attendance = @employee.attendances.find(params[:id])

    @attendance.destroy
    redirect_to attendances_url, notice: 'Attendance was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_attendance
      @attendance = Attendance.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def attendance_params
      params.require(:attendance).permit(:event, :latitude, :longitude, :marked_at)
    end
end

app/helpers/attendances_helper.rb
module AttendancesHelper
end

app/views/attendances/_form.html.erb
<%= form_for([@employee, @employee.attendances.build]) do |f| %>
<% if @attendance.errors.any? %>
<div id="error_explanation">
    <h2><%= pluralize(@attendance.errors.count, "error") %> prohibited this attendance from being saved:</h2>

    <ul>
        <% @attendance.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
        <% end %>
    </ul>
</div>
<% end %>

<div class="form-group">
                <%= f.label :event %>
            <%= f.text_field :event, :class => "form-control" %>
    </div>
<div class="form-group">
                <%= f.label :latitude %>
            <%= f.text_field :latitude, :class => "form-control" %>
    </div>
<div class="form-group">
                <%= f.label :longitude %>
            <%= f.text_field :longitude, :class => "form-control" %>
    </div>
<div class="form-group">
                <%= f.label :marked_at %>
            <%= f.datetime_select :marked_at, :class => "form-control" %>
    </div>
<!-- <div class="form-group">
                <= f.label :employee_id %>
            <= f.collection_select :employee_id, Employee.all, :id, :run, prompt: true, :class => 'form-control'  %>
    </div> -->
<div class="actions">
    <%= f.submit :class => "btn btn-success" %>
</div>
<% end %>

app/views/attendances/edit.html.erb
<h1>Editing attendance</h1>

<%= render 'form' %>

<%= link_to 'Show', [@employee, @employee.attendances.build], :class => "bnt btn-link" %> |
<%= link_to 'Back', employee_attendances_path(@employee), :class => "btn btn-link" %>

app/views/attendances/index.html.erb
<h2 class="page-title page-title-green">
  <span class="glyphicon glyphicon-align-left"></span>
  attendances
</h2>

<div class="page-buttons clearfix">
  <%= link_to 'New Attendance', new_employee_attendance_path, :class => "btn btn-primary float-left" %>
</div>

<div class="page-body">
  <div class="panel panel-default">
    <div class="panel-body">
      <div class="table-responsive">

        <table class="table table-hover">
          <thead>
            <tr>
                              <th>Enento</th>
                              <th>Latitud</th>
                              <th>Longitud</th>
                              <th>Fecha y hora de marcado</th>
                              <!-- <th>Employee</th> -->
                            <th></th>              
            </tr>
          </thead>

          <tbody>
            <% @employee.attendances.order("marked_at desc").each do |attendance| %>
              <tr>
                                    <td><%= attendance.event %></td>
                                    <td><%= attendance.latitude %></td>
                                    <td><%= attendance.longitude %></td>
                                    <td><%= attendance.marked_at %></td>
                                    <!-- <td><%= attendance.employee.run %></td> -->
                                <td><%= link_to '', employee_attendance_path(@employee, attendance), :class => "btn btn-default glyphicon glyphicon-eye-open" %></td>
                <!-- <td><= link_to 'Edit', edit_attendance_path(attendance) %></td>
                <td><= link_to 'Destroy', attendance, method: :delete, data: { confirm: 'Are you sure?' } %></td> -->
              </tr>
            <% end %>
          </tbody>
        </table>

      </div>
    </div>
  </div>
</div>

<br>

app/views/attendances/new.html.erb
<h1>New attendance</h1>

<%= render 'form' %>

<%= link_to 'Back', employee_attendances_path(@employee), :class => "btn btn-link" %>

app/views/attendances/show.html.erb
<h2 class="page-title page-title-green">
	<span class="glyphicon glyphicon-map-marker"></span>
	asistencia
</h2>
<br />
<ol class="breadcrumb">
  <li><%= link_to "Empleado", employee_path(@employee) %></li>
  <li class="active">Asistencia <b><%= @attendance.marked_at %></b></li>
</ol>

<div class="page-body">
	<div class="row">
		<div class="col-md-12">

			<div class="panel panel-success">
				<div class="panel-heading">Posición del empleado</div>
				<div class="panel-body">
					<center>
						<div id="map" class="map" style="height: 350px; width: 700px; border-style: solid; border-width: 1px; float: center;"></div>
					</center>
				</div>
			</div>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
<script src="https://maps.googleapis.com/maps/api/js?v=3.exp&sensor=false&callback=initialize"></script>
<script>


/* API Google Maps*/

var directionsDisplay,
    directionsService,
    map;

function initialize() {
	var directionsService = new google.maps.DirectionsService();
	var directionsDisplay = new google.maps.DirectionsRenderer();
	var center = new google.maps.LatLng("<%= @attendance.latitude %>","<%= @attendance.longitude %>");
	var marker_position = new google.maps.LatLng("<%= @attendance.latitude %>","<%= @attendance.longitude %>")
	var mapOptions = {
	    zoom: 15,
	    mapTypeId: google.maps.MapTypeId.ROADMAP,
	    center: center,
	    mapTypeControl: false,
	    panControl: false,
	    zoomControl: true,
	    streetViewControl: true
	}
	var infowindow = new google.maps.InfoWindow()    

	map = new google.maps.Map(document.getElementById("map"), mapOptions);
	directionsDisplay.setMap(map);
	marker = new google.maps.Marker({ position: marker_position, map: map, title: 'Empleado'})
	infowindow.setContent('<span class="dark">Empleado run: <%= @employee.run %></span>')
	infowindow.open(map, marker)

	google.maps.event.addListener(marker , 'click', function () {
	    infowindow.open(map, marker)
    })
}

</script>



			<div class="panel panel-success">
				<div class="panel-heading">Detalle asistencia</div>
				<div class="panel-body">

					<div class="row">
						<div class="col-md-6">
							<table class="table">
								<tbody>
																			<tr>
										  <th>Evento:</th>
										  <td><%= @attendance.event %></td>
										</tr>
																			<tr>
										  <th>Latitud:</th>
										  <td><%= @attendance.latitude %></td>
										</tr>
																			<tr>
										  <th>Longitud:</th>
										  <td><%= @attendance.longitude %></td>
										</tr>
																			<tr>
										  <th>Fecha y hora de marcado:</th>
										  <td><%= @attendance.marked_at %></td>
										</tr>
											<!-- 								<tr>
											<th>Employee:</th>
											<td><= @attendance.employee.name %></td>
										</tr> -->
																	</tbody>
							</table>
						</div>

					</div>
<!-- 
<= link_to 'Editar', edit_employee_attendance_path(@employee, @attendance), :class => "btn btn-default" %> -->
<%= link_to 'Destruir', [@attendance.employee, @attendance], method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-danger" %>
<%= link_to 'Volver', employee_path(@employee), :class => "btn btn-link" %>

				</div>
			</div>
		</div>
	</div>
	
</div>